// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbeLHQ4dvBzIsS1MgC-EMGOkDDGvaUhRA',
    appId: '1:53704464362:web:68ca6e3d972718644a8493',
    messagingSenderId: '53704464362',
    projectId: 'edotalenthubapp',
    authDomain: 'edotalenthubapp.firebaseapp.com',
    storageBucket: 'edotalenthubapp.appspot.com',
    measurementId: 'G-SJG7R3V50L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbeLHQ4dvBzIsS1MgC-EMGOkDDGvaUhRA',
    appId: '1:53704464362:android:68ca6e3d972718644a8493',
    messagingSenderId: '53704464362',
    projectId: 'edotalenthubapp',
    storageBucket: 'edotalenthubapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbeLHQ4dvBzIsS1MgC-EMGOkDDGvaUhRA',
    appId: '1:53704464362:ios:68ca6e3d972718644a8493',
    messagingSenderId: '53704464362',
    projectId: 'edotalenthubapp',
    storageBucket: 'edotalenthubapp.appspot.com',
    iosBundleId: 'com.edotalenthub.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbeLHQ4dvBzIsS1MgC-EMGOkDDGvaUhRA',
    appId: '1:53704464362:macos:68ca6e3d972718644a8493',
    messagingSenderId: '53704464362',
    projectId: 'edotalenthubapp',
    storageBucket: 'edotalenthubapp.appspot.com',
    iosBundleId: 'com.edotalenthub.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbeLHQ4dvBzIsS1MgC-EMGOkDDGvaUhRA',
    appId: '1:53704464362:windows:68ca6e3d972718644a8493',
    messagingSenderId: '53704464362',
    projectId: 'edotalenthubapp',
    storageBucket: 'edotalenthubapp.appspot.com',
  );
} 